---
  name: 'Format Code: ensure code formatting guidelines are met'
  
  on:
    workflow_dispatch: null
    schedule:
      - cron: 45 4 * * 1-5
  
  permissions:
    contents: write
    pull-requests: write
    actions: write  # Allows automatic commit signing
  
  concurrency:
    group: '${{ github.ref }}-${{ github.workflow }}'
    cancel-in-progress: true
  
  jobs:
    build:
      name: MegaLinter
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            token: '${{ secrets.GITHUB_TOKEN }}'
            fetch-depth: 0
  
        - name: Prepare Git options
          run: bash ./scripts/git-setup.sh
  
        - name: Create new branch
          run: |
            date=$(date +%Y_%m_%d)
            branch_name="format_fixes_$date"
            git checkout -b $branch_name
  
        - name: Run linter
          id: ml
          uses: oxsecurity/megalinter/flavors/terraform@v8.0.0
          env:
            APPLY_FIXES: all
            APPLY_FIXES_EVENT: all
            APPLY_FIXES_MODE: pull_request
            DISABLE_ERRORS: true
            EMAIL_REPORTER: false
            ENABLE_LINTERS: JSON_PRETTIER,YAML_PRETTIER,TERRAFORM_TERRAFORM_FMT,MARKDOWN_MARKDOWNLINT
            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            VALIDATE_ALL_CODEBASE: true
            YAML_PRETTIER_FILTER_REGEX_EXCLUDE: (.github/*)
            MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (terraform/modules/.*/.*.md)
            REPORT_OUTPUT_FOLDER: none
  
        - name: Check for changes
          run: |
            git add .
            git commit -m "Automated formatting fixes from GitHub Actions" || true
            branch_name=$(git branch --show-current)
            changes=$(git diff origin/main...$branch_name --name-only)
            if [ -z "$changes" ]; then
              echo "No changes detected."
            else
              echo "Changes detected."
              echo "changes=true" >> $GITHUB_ENV
            fi
  
        - name: Push changes
          if: env.changes == 'true'
          run: |
            git config --global push.autoSetupRemote true
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
        - name: Create pull request
          if: env.changes == 'true'
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            pr_title="Automated code formatting updates"
            pr_body="This PR contains formatting fixes applied by the Format Code GitHub Actions workflow."
            branch_name=$(git branch --show-current)
            pr_head="${{ github.repository_owner }}:${branch_name}"
            pr_base="main"
            gh pr create --title "$pr_title" --body "$pr_body" --head "$pr_head" --base "$pr_base" --label "code quality"
  
        # Optionally, call GitHub GraphQL API for further operations (optional)
        - name: Call GitHub GraphQL API
          run: |
            curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -X POST \
                 -d '{"query": "query { repository(owner:\"${{ github.repository_owner }}\", name:\"${{ github.event.repository.name }}\") { object(expression:\"main\") { ... on Commit { history(first: 5) { edges { node { message } } } } } } }"}' \
                 https://api.github.com/graphql
  