name: Generate dependabot file Signed Commits

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  create-and-commit-dependabot-file:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Generate Dependabot file
        run: bash ./scripts/generate-dependabot-file.sh

      - name: Set up Git user
        run: bash ./scripts/git-setup.sh

      - name: Debug: Show Git Status
        run: |
          echo "===== Git Status ====="
          git status
          echo "===== Changed Files ====="
          git diff --name-only

      - name: Commit and Create PR with Signed Commit
        uses: ministryofjustice/modernisation-platform-github-actions/signed-commit@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated Update: Dependabot File"
          pr_body: "This PR updates the Dependabot configuration file."
