name: Generate dependabot file Signed Commits

on:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  create-and-commit-dependabot-file:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      
      - name: Generate Dependabot file
        run: bash ./scripts/generate-dependabot-file.sh

      - name: Call Signed Commit & PR Workflow
        uses: ./.github/workflows/reusable-signed-commit.yml
        with:
          pr_title: "Automated Update: Dependabot File"
          pr_body: "This PR updates the Dependabot configuration file."
