---
  name: check user guide links

  on:
    pull_request: 
      paths:
        - "source/**"

  permissions: {}
  jobs:
    check-links:
      name: Test
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

        - name: Lychee
          id: lychee
          uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.erb' --exclude-loopback --accept 403,200,429
            fail: true