name: New member environment files

on:
  push:
    paths:
      - 'environments/**.json'
      - 'environments-networks/**.json'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  fetch-secrets:
    permissions:
      id-token: write
    uses: ministryofjustice/modernisation-platform-github-actions/.github/workflows/aws-secrets-management.yml@cf6e13565dc769b53644a230561ea14bfbc70008 # v3.0.0
    secrets:
      MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}  

  create-and-commit-files:
    runs-on: ubuntu-latest
    needs: fetch-secrets
    steps:
      - name: Decrypt Secrets
        uses: ministryofjustice/modernisation-platform-github-actions/decrypt-secrets@cf6e13565dc769b53644a230561ea14bfbc70008 # v3.0.0
        with:
          slack_webhook_url: ${{ needs.fetch-secrets.outputs.slack_webhook_url }}
          terraform_github_token: ${{ needs.fetch-secrets.outputs.terraform_github_token }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: core-repo
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ministryofjustice/modernisation-platform-environments
          path: modernisation-platform-environments
          persist-credentials: false
        env:  
          TERRAFORM_GITHUB_TOKEN: ${{ env.TERRAFORM_GITHUB_TOKEN }}
      - name: Provision member environment directories
        run: bash ./core-repo/scripts/provision-member-directories.sh
      - name: Setup GitHub
        run: bash ./core-repo/scripts/git-setup.sh ./modernisation-platform-environments
      - name: Commit and Create PR with Signed Commit
        uses: ministryofjustice/modernisation-platform-github-actions/signed-commit@cf6e13565dc769b53644a230561ea14bfbc70008 # v3.0.0
        with:
          github_token: ${{ secrets.TERRAFORM_GITHUB_TOKEN }} # use this token as writing to a different repo
          git_path: "terraform/environments"
          remote_repository: "ministryofjustice/modernisation-platform-environments"
          remote_repository_path: "./modernisation-platform-environments"
          pr_title: "New files for terraform/environments"
          pr_body: "> This PR was automatically created via a GitHub action workflow 🤖"
      - name: Slack failure notification
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          webhook-type: incoming-webhook
          payload: |
            {"blocks":[{"type": "section","text": {"type": "mrkdwn","text": ":no_entry: Failed GitHub Action:"}},{"type": "section","fields":[{"type": "mrkdwn","text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"},{"type": "mrkdwn","text": "*Job:*\n${{ github.job }}"},{"type": "mrkdwn","text": "*Repo:*\n${{ github.repository }}"}]}]}
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}
