name: Send Message on Onboarding Issue Close

on:
  workflow_dispatch:
  issues:
    types:
      - closed

permissions:
  contents: read

jobs:
  send-message:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20
      - name: Send message to user on onboarding issue close
        env:
          github-token: "${{ secrets.GITHUB_TOKEN }}"       
        if: contains(github.event.issue.labels.*.name, 'onboarding') && github.event.issue.state == 'closed'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            // app.js
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Hello @${{ github.event.issue.user.login }} 👋 Welcome to the Modernisation Platform! Your new accounts have now been created. \
                   Please see our [user guidance](https://user-guide.modernisation-platform.service.justice.gov.uk/#getting-started) for details on how to build and access infrastructure in the Modernisation Platform. \
                   If you require help or assistance please contact us via the [#ask-modernisation-platform]((https://moj.enterprise.slack.com/archives/C01A7QK5VM1)) Slack channel. '
            });
