name: reusable terraform plan apply
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      aws-region:
        required: false
        type: string
        default: "eu-west-2"
    secrets:
      modernisation_platform_environments:
        required: true
      gh_workflow_token: 
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      pagerduty_token:
        required: false
      pagerduty_userapi_token:
        required: false

env:
  ENVIRONMENT_MANAGEMENT: "${{ secrets.modernisation_platform_environments }}"
  TF_VAR_github_token: "${{ secrets.gh_workflow_token }}"
  TF_IN_AUTOMATION: true
  TF_VAR_pagerduty_token: ${{ secrets.pagerduty_token }}
  TF_VAR_pagerduty_user_token: ${{ secrets.pagerduty_userapi_token }}

jobs:
  plan-and-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set Account Number
        run: echo "ACCOUNT_NUMBER=$(jq -r -e '.modernisation_platform_account_id' <<< $ENVIRONMENT_MANAGEMENT)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
          role-session-name: githubactionsrolesession
          aws-region: ${{ inputs.aws-region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: "~1"
          terraform_wrapper: false

      - name: terraform init
        run: bash scripts/terraform-init.sh ${{ inputs.working_directory }}

      - name: terraform plan
        run: bash scripts/terraform-plan.sh ${{ inputs.working_directory }}

      - name: terraform apply
        if: github.event.ref == 'refs/heads/main'
        run: bash scripts/terraform-apply.sh ${{ inputs.working_directory }}

      - name: Slack failure notification
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          payload: |
            {"blocks":[{"type": "section","text": {"type": "mrkdwn","text": ":no_entry: Failed GitHub Action:"}},{"type": "section","fields":[{"type": "mrkdwn","text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"},{"type": "mrkdwn","text": "*Job:*\n${{ github.job }}"},{"type": "mrkdwn","text": "*Repo:*\n${{ github.repository }}"}]}]}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK