name: Notify Slack with SecurityHub Findings Summary

on:
  schedule:
    # trigger every weekday at 08:30am
    - cron: '30 8 * * 1-5'
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

defaults:
  run:
    shell: bash

jobs:

  fetch-secrets:
    uses: ministryofjustice/modernisation-platform-github-actions/.github/workflows/aws-secrets-management.yml@4eceb2a416a197e91dc557c2ef0b5dd9afe29e0c # v3.4.6
    secrets:
        MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}

  generate-account-matrix-blocks:
    runs-on: ubuntu-latest
    needs: fetch-secrets
    outputs:
      matrix-group-1: ${{ steps.generate-account-matrix-blocks.outputs.block_1 }}
      matrix-group-2: ${{ steps.generate-account-matrix-blocks.outputs.block_2 }}
      matrix-group-3: ${{ steps.generate-account-matrix-blocks.outputs.block_3 }}
      matrix-group-4: ${{ steps.generate-account-matrix-blocks.outputs.block_4 }}
    steps:
      - name: Decrypt Secrets
        uses: ministryofjustice/modernisation-platform-github-actions/decrypt-secrets@4eceb2a416a197e91dc557c2ef0b5dd9afe29e0c # v3.4.6
        with:
          environment_management: ${{ needs.fetch-secrets.outputs.environment_management }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Generate Account List from Secret
        id: generate-account-list
        run: |
          set -euo pipefail
          MATRIX_JSON=$(jq -c '[.account_ids | to_entries[] | {name: .key}]' <<< "$ENVIRONMENT_MANAGEMENT")
          echo "matrix=$MATRIX_JSON" >> "$GITHUB_OUTPUT"

      - name: Generate Account Matrix Blocks
        id: generate-account-matrix-blocks
        env:
          account_list: ${{ steps.generate-account-list.outputs.matrix }}
        run: |
          set -euo pipefail
          BLOCK_COUNT=4
          sorted=$(echo "$account_list" | jq -c 'sort')
          total=$(echo "$sorted" | jq 'length')
          base=$(( total / BLOCK_COUNT ))
          remainder=$(( total % BLOCK_COUNT ))
          start=0
          for i in $(seq 1 $BLOCK_COUNT); do
            key="block_$i"
            # Distribute remainder
            extra=0
            if [ "$i" -le "$remainder" ]; then
              extra=1
            fi
            end=$(( start + base + extra ))
            block=$(echo "$sorted" | jq ".[$start:$end]")
            compact=$(echo "$block" | jq -c '.')
            echo "::group::$key"
            echo "$block" | jq .
            echo "::endgroup::"
            echo "$key=$compact" >> "$GITHUB_OUTPUT"
            start=$end
          done


  process-security-findings-1:
    name: ${{ matrix.account.name }}
    needs: [fetch-secrets, generate-account-matrix-blocks]
    strategy:
      matrix:
        account: ${{ fromJson(needs.generate-account-matrix-blocks.outputs.matrix-group-1) }}
    uses: ./.github/workflows/reusable-securityhub-findings.yml
    with:
      account_name: ${{ matrix.account.name }}
      aws_region: "eu-west-2"
      environment_management: ${{ needs.fetch-secrets.outputs.environment_management }}
      slack_webhook_url: ${{ needs.fetch-secrets.outputs.securityhub_slack_webhooks }}
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}

  process-security-findings-2:
    name: ${{ matrix.account.name }}
    needs: [fetch-secrets, generate-account-matrix-blocks]
    strategy:
      matrix:
        account: ${{ fromJson(needs.generate-account-matrix-blocks.outputs.matrix-group-2) }}
    uses: ./.github/workflows/reusable-securityhub-findings.yml
    with:
      account_name: ${{ matrix.account.name }}
      aws_region: "eu-west-2"
      environment_management: ${{ needs.fetch-secrets.outputs.environment_management }}
      slack_webhook_url: ${{ needs.fetch-secrets.outputs.securityhub_slack_webhooks }}
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}

  process-security-findings-3:
    name: ${{ matrix.account.name }}
    needs: [fetch-secrets, generate-account-matrix-blocks]
    strategy:
      matrix:
        account: ${{ fromJson(needs.generate-account-matrix-blocks.outputs.matrix-group-3) }}
    uses: ./.github/workflows/reusable-securityhub-findings.yml
    with:
      account_name: ${{ matrix.account.name }}
      aws_region: "eu-west-2"
      environment_management: ${{ needs.fetch-secrets.outputs.environment_management }}
      slack_webhook_url: ${{ needs.fetch-secrets.outputs.securityhub_slack_webhooks }}
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}

  process-security-findings-4:
    name: ${{ matrix.account.name }}
    needs: [fetch-secrets, generate-account-matrix-blocks]
    strategy:
      matrix:
        account: ${{ fromJson(needs.generate-account-matrix-blocks.outputs.matrix-group-4) }}
    uses: ./.github/workflows/reusable-securityhub-findings.yml
    with:
      account_name: ${{ matrix.account.name }}
      aws_region: "eu-west-2"
      environment_management: ${{ needs.fetch-secrets.outputs.environment_management }}
      slack_webhook_url: ${{ needs.fetch-secrets.outputs.securityhub_slack_webhooks }}
    secrets:
      passphrase: ${{ secrets.PASSPHRASE }}


