name: "Terraform: PagerDuty resources"

on:
  push:
    paths:
      - 'terraform/pagerduty/**'
      - '.github/workflows/terraform-pagerduty.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'terraform/pagerduty/**'
      - '.github/workflows/terraform-pagerduty.yml'
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

defaults:
  run:
    shell: bash

jobs:
  pagerduty-plan-and-apply:
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      working-directory: "terraform/pagerduty"
    secrets:
      modernisation_platform_environments: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}
      gh_workflow_token: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
      pagerduty_token: ${{ secrets.PAGERDUTY_TOKEN }}
      pagerduty_userapi_token: ${{ secrets.PAGERDUTY_USERAPI_TOKEN}}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}