name: Update Securityhub Slack Secret
on:
  workflow_dispatch:
    inputs:
      application:
        description: "Application name (eg: sprinkler)"
        required: true
      slack_webhook_url:
        description: "Slack webhook URL"
        required: true
env:
  AWS_REGION: "eu-west-2"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}:role/github-actions-apply"
          role-session-name: githubactionsrolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: MASK Slack webhook
        run: |
          slack_webhook_url=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.slack_webhook_url' )
          echo "::add-mask::$slack_webhook_url" 
           echo "SLACK_WEBHOOK_URL=$slack_webhook_url" >> $GITHUB_ENV
      - name: Run Secret Update Script
        run: ./scripts/update_securityhub_secret.sh ${{ github.event.inputs.application }} ${{ env.SLACK_WEBHOOK_URL }}
